# Generated by Django 5.2.7 on 2025-12-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBookStore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='publisher_logos/'),
        ),
    ]
