# Generated by Django 5.2.7 on 2025-12-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBookStore', '0002_publisher_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='author_photos/'),
        ),
    ]
